apiVersion: v1
data:
    userData: ewogICAgImlnbml0aW9uIjogewogICAgICAgICJjb25maWciOiB7fSwKICAgICAgICAidmVyc2lvbiI6ICIyLjIuMCIKICAgIH0sCiAgICAibmV0d29ya2QiOiB7fSwKICAgICJwYXNzd2QiOiB7CiAgICAgICAgInVzZXJzIjogWwogICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAibmFtZSI6ICJjb3JlIiwKICAgICAgICAgICAgICAgICJzc2hBdXRob3JpemVkS2V5cyI6IFsKICAgICAgICAgICAgICAgICAgICAic3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCQVFDL0F2TTlWYk8yeWlJYjlBaWxsQnAva1RyOGpxSUVyUlUxTEZLcWh3UFRtNEF0VklqRlNhT3VNNEFsc3BmQ1VJejlJSEJyRGNabWJjWUthaTNsQzNKdFFpYzdNL2ExT1dValdFMU1MOENFdk5zR1BHdTV5TlZVUW9XQzBsbVc1cnpYOWM2SHZIOEFjbWZNbWR5UTdTZ2NBbmswemlyOWp3OGVkMlRSQXpIbjN2WEZkNytzYVpMaWhGSmhYRzR6Qjh2aDdnSkhqTGZqSWEzSkhwdFd6VzlBdHFGOVFzb0JZL2l1NThSZi9oUm5yZldzY3lOM3g5cEdDU0VxZExTRHY3SEZ1SDJFYWJudk5GRlFacjRKMUZZekgvZktWWTNQcHQzcmY2NFVXQ3p0RHU3TDQ0ZlB3d2tJN25BemRtUVZUYU1vRDNFajhpNy9PU0Zac0MyVjVJQlQga2JvdW1lZGhAYnVtYmxlZm9vdCIKICAgICAgICAgICAgICAgIF0KICAgICAgICAgICAgfSwKICAgICAgICAgICAgewogICAgICAgICAgICAgICAgIm5hbWUiOiAicm9vdCIsCiAgICAgICAgICAgICAgICAic3NoQXV0aG9yaXplZEtleXMiOiBbCiAgICAgICAgICAgICAgICAgICAgInNzaC1yc2EgQUFBQUIzTnphQzF5YzJFQUFBQURBUUFCQUFBQkFRQy9Bdk05VmJPMnlpSWI5QWlsbEJwL2tUcjhqcUlFclJVMUxGS3Fod1BUbTRBdFZJakZTYU91TTRBbHNwZkNVSXo5SUhCckRjWm1iY1lLYWkzbEMzSnRRaWM3TS9hMU9XVWpXRTFNTDhDRXZOc0dQR3U1eU5WVVFvV0MwbG1XNXJ6WDljNkh2SDhBY21mTW1keVE3U2djQW5rMHppcjlqdzhlZDJUUkF6SG4zdlhGZDcrc2FaTGloRkpoWEc0ekI4dmg3Z0pIakxmaklhM0pIcHRXelc5QXRxRjlRc29CWS9pdTU4UmYvaFJucmZXc2N5TjN4OXBHQ1NFcWRMU0R2N0hGdUgyRWFibnZORkZRWnI0SjFGWXpIL2ZLVlkzUHB0M3JmNjRVV0N6dER1N0w0NGZQd3drSTduQXpkbVFWVGFNb0QzRWo4aTcvT1NGWnNDMlY1SUJUIGtib3VtZWRoQGJ1bWJsZWZvb3QiCiAgICAgICAgICAgICAgICBdCiAgICAgICAgICAgIH0KICAgICAgICBdCiAgICB9LAogICAgInN0b3JhZ2UiOiB7CiAgICAgICAgImZpbGVzIjogWwogICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAiY29udGVudHMiOiB7CiAgICAgICAgICAgICAgICAgICAgInNvdXJjZSI6ICJkYXRhOixrbmktbm9kZTAyJTBBIiwKICAgICAgICAgICAgICAgICAgICAidmVyaWZpY2F0aW9uIjoge30KICAgICAgICAgICAgICAgIH0sCiAgICAgICAgICAgICAgICAiZmlsZXN5c3RlbSI6ICJyb290IiwKICAgICAgICAgICAgICAgICJtb2RlIjogNDIwLAogICAgICAgICAgICAgICAgIm92ZXJ3cml0ZSI6IHRydWUsCiAgICAgICAgICAgICAgICAicGF0aCI6ICIvZXRjL2hvc3RuYW1lIgogICAgICAgICAgICB9LAogICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAiY29udGVudHMiOiB7CiAgICAgICAgICAgICAgICAgICAgInNvdXJjZSI6ICJkYXRhOiwlMjMlMjEvYmluL3NoJTBBZWNobyUyMHVuaXgxMjM0JTIwJTdDJTIwcGFzc3dkJTIwLS1zdGRpbiUyMHJvb3QlMEEiLAogICAgICAgICAgICAgICAgICAgICJ2ZXJpZmljYXRpb24iOiB7fQogICAgICAgICAgICAgICAgfSwKICAgICAgICAgICAgICAgICJmaWxlc3lzdGVtIjogInJvb3QiLAogICAgICAgICAgICAgICAgIm1vZGUiOiA0NDgsCiAgICAgICAgICAgICAgICAicGF0aCI6ICIvdXNyL2xvY2FsL2Jpbi9maXJzdC5zaCIKICAgICAgICAgICAgfQogICAgICAgIF0KICAgIH0sCiAgICAic3lzdGVtZCI6IHsKICAgICAgICAidW5pdHMiOiBbCiAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgICJjb250ZW50cyI6ICJbU2VydmljZV1cblR5cGU9b25lc2hvdFxuRXhlY1N0YXJ0PS91c3IvbG9jYWwvYmluL2ZpcnN0LnNoXG5bSW5zdGFsbF1cbldhbnRlZEJ5PW11bHRpLXVzZXIudGFyZ2V0XG4iLAogICAgICAgICAgICAgICAgImVuYWJsZWQiOiB0cnVlLAogICAgICAgICAgICAgICAgIm5hbWUiOiAiZmlyc3QtYm9vdC5zZXJ2aWNlIgogICAgICAgICAgICB9CiAgICAgICAgXQogICAgfQp9Cg==
kind: Secret
metadata:
  name: kni-node02-user-data
  namespace: metal3
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: kni-node02-credentials
  namespace: metal3
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW4=
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: kni-node02
  namespace: metal3
spec:
  bmc:
    address: ipmi://172.22.0.1:6231
    credentialsName: kni-node02-credentials
  image:
    url: http://172.22.0.1/images/rhcos.qcow2
    checksum: http://172.22.0.1/images/rhcos.qcow2.md5sum
  userData:
    name: kni-node02-user-data
    namespace: metal3
  bootMACAddress: 00:c2:fc:3b:e1:02
  description: ""
  hardwareProfile: "libvirt"
  online: true
