apiVersion: v1	
kind: Secret	
metadata:	
  name: metal3-node01-credentials	
  namespace: metal3	
type: Opaque	
data:	
  username: YWRtaW4=	
  password: YWRtaW4=	
---	
apiVersion: metal3.io/v1alpha1	
kind: BareMetalHost	
metadata:	
  name: metal3-node01	
  namespace: metal3	
spec:	
  bmc:	
    address: ipmi://172.22.0.2:6230	
    credentialsName: metal3-node01-credentials	
  bootMACAddress: 00:c2:fc:3b:e1:01	
  description: ""	
  hardwareProfile: "libvirt"	
  online: false
