apiVersion: v1
kind: Service
metadata:
  name: tvshows-web
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30000
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    kubevirt.io/domain: tvshows
  sessionAffinity: None
  type: NodePort
