apiVersion: v1
kind: Service
metadata:
  name: tvshows-web-v2
  namespace: default
spec:
  ports:
  - name: tvshows-v2
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: tvshows
  type: LoadBalancer
